on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: tabloulet
  PROJECT_PATH: .

jobs:
  export-linux-windows:
    name: Linux and Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-4.3
    steps:
      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Linux and Windows Export
        run: |
          mkdir -v -p build/linux
          mkdir -v -p build/windows
          EXPORT_DIR_LINUX="$(readlink -f build)"
          EXPORT_DIR_WINDOWS="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --import --export-release "Linux" "$EXPORT_DIR_LINUX/linux/$EXPORT_NAME.x86_64"
          godot --headless --verbose --import --export-release "Windows" "$EXPORT_DIR_WINDOWS/windows/$EXPORT_NAME.exe"
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows